### ISSUE TITLE
File.current_offset is private to the crate and there is no tell()

### ISSUE THREAD

**Issue by Jajcus** [rust-embedded-community/embedded-sdmmc-rs#101]
The File object provides handy ``seek_*()`` methods to move to a specific position, but there is no ``tell()`` method to get the current position. This forces client applications to track file offsets themselves or use ``f.size() - f.left()``.

**Comment by jonathanpallant** [comment]
Oops. Feel like sending a PR?

**Comment by Jajcus** [comment]
Sure! I guess even Rust newbie like me can handle this one. :-)

**Comment by Jajcus** [comment]
Oh… current git version is different than the released on – there are no File methods at all.

I guess this has to wait until  #99 is resolved.

**Comment by Jajcus** [comment]
Oh… there already is VolumeManager.file_offset() method. So I guess that has been already solved.

**Comment by thejpster** [comment]
Oh, nice. I'd forgotten about that.
