### ISSUE TITLE
new() without chip-select?

### ISSUE THREAD

**Issue by theAntimon** [rust-embedded-community/embedded-sdmmc-rs#130]
Hi, I'm looking for a way to use the package without providing an extra pin for chip select. I have only one SPI devide on my RP pico and can therefore pull the CS pin hard to ground. I have no other pin left to use for chip select. What can I do?

**Comment by thejpster** [comment]
You can't pull the CS hard to ground according to the spec as you need to send a bunch of clock pulses at 400 kHz with CS de-asserted in order to enter SPI mode.

But if you really want to, just impl the appropriate trait on a dummy type and pass a value of that type.

**Comment by theAntimon** [comment]
Ok, thank you for the answer. I finally made it by implementing the trait.
