### ISSUE TITLE
Consider an appropriate MSRV

### ISSUE THREAD

**Issue by elpiel** [rust-embedded-community/embedded-sdmmc-rs#166]
Since we are moving forward with implementations that will bring async support I think it's good time to talk about MSRV.

`async_fn_in_trait` has been stabalised in `1.75.0` and I think we can start from there.
I can:
- [ ] tweak the CI to include MSRV build
as well as
- [ ] change the Cargo.toml to include `rust-version = "1.75"`

**Comment by thejpster** [comment]
I'm fine with either 1.75, or [Ferrocene 24.05](https://ferrous-systems.com/blog/ferrocene-24-05-0/) (which is based off [1.76](https://blog.rust-lang.org/2024/02/08/Rust-1.76.0.html)).
