### ISSUE TITLE
Reinitialization support

### ISSUE THREAD

**Issue by ostenning** [rust-embedded-community/embedded-sdmmc-rs#34]
Hey, I'm using this library in conjunction with an SDIO SDMMC controller and a removable SDCard.

I would like to be able to reinitialize this library if the user removes the SDCard and reinserts it.

What I am doing is:

1. Initialize everything, the SDMMC and this library, with SDCard present  ✅ 
2. Remove the SDCard, and then reinsert it (or another card) ✅ 
4. Reinitialize the SDMMC controller ✅ 
5. Reinitialize this library ❌ 

I need to refresh the handles for the Volume, e.g:

`let mut volume = self.controller.get_volume(VolumeIdx(0)).unwrap();`

But I then encounter the error:

`panicked at 'called Result::unwrap() on an Err value: FormatError("Invalid MBR signature")', src/drivers/sdcard.rs:117:67`

**Proposed solution:**

Either allow the `Controller` and volumes to be reinitialized, or provide a means to relinquish the block device so that the `Controller` can be reinitialized from scratch.

Kind regards

**Comment by thejpster** [comment]
Closed by #80, I think. You probably need out-of-band support to know when to destroy your VolumeManager though.
