### ISSUE TITLE
Version release

### ISSUE THREAD

**Issue by ostenning** [rust-embedded-community/embedded-sdmmc-rs#52]
@thejpster there hasn't been a release on crates.io for quite a long time. Some features on the HEAD, such as deletion of files is not accessible for those using the crate directly from the crates.io.

Is it possible to schedule a new release soon?

Kind regards

**Comment by thejpster** [comment]
Good idea! Not sure when I’ll have time, but that’s why the crate lives here - so there’s others who can press the buttons as well.

**Comment by ostenning** [comment]
> Good idea! Not sure when I’ll have time, but that’s why the crate lives here - so there’s others who can press the buttons as well.

I'm not entirely sure what the release etiquette surrounding project dependencies is. The issue I'm facing is that the [stm32h7xx_hal uses the 0.0.3 version from crates.io](https://github.com/stm32-rs/stm32h7xx-hal/blob/6698c1f423ef40d6eb8697b774ad923858d23e8a/Cargo.toml#L41) 

I can suggest to the stm32h7xx HAL maintainers to use this repository directly if that is what you recommend.

Thanks!

**Comment by thejpster** [comment]
You can't publish to crates.io with a git dependency, so we should probably do a new release. Anyone in r-e-c should be able to do that - I have very limited time right now.

**Comment by thejpster** [comment]
See #57
