### ISSUE TITLE
Make functions that modify underlying state through SPI receive `&mut self` instead of `&self`

### ISSUE THREAD

**Issue by datdenkikniet** [rust-embedded-community/embedded-sdmmc-rs#55]
Currently, `BlockDevice::read` and `BlockDevice::write`  (and practically all functions in `SdMmcSpi` and `BlockSpi`) receive `&self`.

Why is this done? 

In my opinion, they should receive `&mut self`, so that responsibility of choosing what method of resource sharing a user wants is up to the user. Issues such as #37 could easily be avoided, and would also make more sense logically: `write`ing something is clearly modifying something, so why does it not need mutable access?

Especially in embedded settings (which this crate is intended for), where being interrupted while having a borrow is quite possible, I don't quite understand why this design choice was made.

I'm willing to contribute a design proposal and  PRs to make this change, if it is deemed that this change makes sense.

This issue is, in essence, the same as #8, but for slightly different reasons. I hope that the reasons mentioned there may have disappeared in the mean time (I can't find a concrete example of why it was dismissed back then). If these issues persist, I would propose that we *clearly* document that `SdMmcSpi` makes use of `RefCell`s internally.

**Comment by datdenkikniet** [comment]
I also looked through some of the dependents on crates.io:

The only implementor of `BlockDevice` that I could find was in `stm32h7xx-hal` (the rest use it only in examples), and that uses the same `RefCell` hack to get around the non-mutability problem

**Comment by datdenkikniet** [comment]
I'm working on an alternative implementation here:

https://github.com/datdenkikniet/embedded-sdmmc-rs/tree/no_more_immutable

**Comment by eldruin** [comment]
Have you looked through the closed issues? There have been related discussions in the past.

**Comment by eldruin** [comment]
Maybe @thejpster has some further reasoning for this interface choice?

**Comment by datdenkikniet** [comment]
Yeah, that's what I was hoping for too :)

**Comment by datdenkikniet** [comment]
I see, thanks for the info!

I'm cooking up a little something, and can ping again here once it's more or less done, and if it seems like the API can be on a similar level of user-friendliness.

So far I've finished implementing reading files and directories, but need to figure out how to do writing and reading at some point while staying ergonomic.

**Comment by datdenkikniet** [comment]
I never did finish my work on this, and with #79 it may not make any sense at all :)

I'm closing this for now
