### ISSUE TITLE
SdMmcSpi::acquire should consume self, not use &mut ref

### ISSUE THREAD

**Issue by ceigel** [rust-embedded-community/embedded-sdmmc-rs#56]
Currently SdMmcSpi::acquire returns a BlockSpi object which contains a mutable reference to the SdMmcSpi. This is a construct that is very hard to work with. I'm reading parts of a file inside an interrupt, so I have to keep alive both a SdMmcSpi and a BlockSpi. Moreover the SdMmcSpi has to be placed in a static variable so that it is not moved once the BlockSpi is constructed. This is quite hard to use.
I believe it would be easier if the SdMmcSpi would be moved inside BlockSpi.

**Comment by gauteh** [comment]
This would make it hard to re-acquire the BlockDeviceSPI in case of some error. I've wrapped the BlockDeviceSpi in a handle which makes it a bit easier to work with: https://github.com/gauteh/sfy/blob/main/sfy-buoy/src/storage/mod.rs#L204, depends on #63 .

**Comment by thejpster** [comment]
Closed by #80
