### ISSUE TITLE
File `starting_cluster` has a value of zero within the `open_files`

### ISSUE THREAD

**Issue by ostenning** [rust-embedded-community/embedded-sdmmc-rs#66]
I've found an issue when trying to close files and open them again. Basically what ends up happening is that upon opening the file, the [`starting_cluster` of the File initialized to zero](https://github.com/rust-embedded-community/embedded-sdmmc-rs/blob/develop/src/controller.rs#L365), and then this zero value [is subsequently set on the `open_files`](https://github.com/rust-embedded-community/embedded-sdmmc-rs/blob/develop/src/controller.rs#L373).

At some point the `starting_cluster` value of the File is adjusted, but the value stored within `open_files` is not. 

Which in turn causes the [`close_file` function within the controller](https://github.com/rust-embedded-community/embedded-sdmmc-rs/blob/develop/src/controller.rs#L576) to not close the file.

If you attempt to open/close files multiple times (beyond the specified `MAX_FILES`) value, the library returns an Error.

I'm trying to figure out a solution to this at the moment. Any help is appreciated. Thanks

**Comment by jbeaurivage** [comment]
I can second that this is happening to me too. It also seems the same thing happens when attempting to close directories.

**Comment by thejpster** [comment]
Oh no. Does the volume this happens on pass a CHKDSK? I didn't think you could have a directory entry pointing at a cluster ID of zero. But I guess anything that /can/ happen on-disk /could/ happen so we should be robust to it.
