### ISSUE TITLE
Add a block cache

### ISSUE THREAD

**Issue by thejpster** [rust-embedded-community/embedded-sdmmc-rs#7]
It would improve performance if we had a write-through block cache, particularly in the cluster allocation loop or for multiple small writes (as we'd avoid the repeated reads).

The user would need to supply the storage, and we just need a basic structure to track which sectors are cached (e.g. a HashMap). Maybe using heapless?

**Comment by thejpster** [comment]
It might also help if read and write were done through closures instead of by copying memory.

**Comment by thalesfragoso** [comment]
The `managed` crate also has some useful structures, and it's used with good success on `smoltcp`.

**Comment by thejpster** [comment]
Closed by #148
