### ISSUE TITLE
README example

### ISSUE THREAD

**Issue by elpiel** [rust-embedded-community/embedded-sdmmc-rs#70]
One of the examples in the readme (the first one) is not correct since it wraps a `SDMmcSpi` inside itself:

`let mut spi_dev = embedded_sdmmc::SdMmcSpi::new(embedded_sdmmc::SdMmcSpi::new(sdmmc_spi, sdmmc_cs), time_source);`

Since the `Controller` is created a few lines below, it seems that this line should simply be:

`let mut spi_dev = embedded_sdmmc::SdMmcSpi::new(sdmmc_spi, sdmmc_cs);`

**Comment by eldruin** [comment]
Indeed. Nice catch.
Would you send a PR fixing this?

**Comment by elpiel** [comment]
Sure thing, I've just open a new PR.
