### ISSUE TITLE
File size update in write doesn't respect seek position

### ISSUE THREAD

**Issue by CBJamo** [rust-embedded-community/embedded-sdmmc-rs#72]
At  [controller#L577](https://github.com/rust-embedded-community/embedded-sdmmc-rs/blob/develop/src/controller.rs#L577) the file size is increased unconditionally. This means that if you've seek-ed back into the file you'll bloat the end of the file with 0s.

**Comment by eldruin** [comment]
Ideas on this @thejpster?

**Comment by thejpster** [comment]
They're right, sounds like a bug. You need to calculate how much you've extended the file by.

```
let new_size = current_pos + amount_written;
if new_size > current_size {
    store(new_size)
}
```
