### ISSUE TITLE
Multiple opened files with empty content triggers `DirAlreadyOpen`

### ISSUE THREAD

**Issue by elpiel** [rust-embedded-community/embedded-sdmmc-rs#75]
Trying to open multiple empty files at the same time with `Controller::open_file_in_dir` in Mode different than `ReadWriteCreate` triggers `open_dir_entry` causes a `DirAlreadyOpen` error.

Is returning `DirAlreadyOpen` a correct response here as well? It seems that it's going over opened files and yet returns `DirAlreadyOpen`?

**Comment by thejpster** [comment]
Damn, I think this is still a bug.

**Comment by thejpster** [comment]
OK fixed it.

**Comment by eldruin** [comment]
Can this be closed now?

**Comment by elpiel** [comment]
I believe so. I saw the issue mentioned in the last PR.
Closing this issue, if any new problems arise someone can open a new issue.
